/**
 * @file CentralPatternGenerator.hpp
 * @author Felipe Mohr (felipe18mohr@gmail.com)
 * @brief Node control a quadruped robot using Central Pattern Generator algorithm
 * @version 1.0
 * @date 2024-08-14
 *
 * @copyright Copyright (c) 2024
 *
 */

#ifndef CENTRAL_PATTERN_GENERATOR_HPP
#define CENTRAL_PATTERN_GENERATOR_HPP

#include "rclcpp/rclcpp.hpp"

#include "geometry_msgs/msg/twist.hpp"
#include "quadruped_interfaces/msg/quadruped_kinematics.hpp"

#include <Eigen/Geometry>
#include <tuple>

#include <memory>

using FeetPositionTuple = std::tuple<Eigen::Vector4d, Eigen::Vector4d, Eigen::Vector4d>;

class CentralPatternGenerator : public rclcpp::Node
{
public:
  CentralPatternGenerator();
  ~CentralPatternGenerator();

private:
  /**
   * @brief Callback function to receive velocity commands and update CPG parameters
   *
   * @param msg A shared pointer to incoming Twist message
   */
  void cmdVelCallback(const geometry_msgs::msg::Twist::SharedPtr msg);

  /** @brief Function to step the CPG and publish the data as an ik command */
  void cmdIKCallback();

  /**
   * @brief Function to step the CPG
   *
   * @param dt The difference of time between the current and the last step
   * @return FeetPositionTuple A tuple with three Eigen::Vector4d with x, y and z foot positions
   */
  FeetPositionTuple updateCPG(double dt);

  /** @brief Subscription to the velocity command */
  std::shared_ptr<rclcpp::Subscription<geometry_msgs::msg::Twist>> cmd_vel_subscriber_;

  /** @brief Publisher to the ik command */
  std::shared_ptr<rclcpp::Publisher<quadruped_interfaces::msg::QuadrupedKinematics>>
      cmd_ik_publisher_;

  /** @brief Timer for periodically publishing the ik command */
  rclcpp::TimerBase::SharedPtr publish_ik_timer_;

  /** @brief The time of the last CPG iteration */
  rclcpp::Time last_time_;

  /** @brief The coupling matrix used to define the gait generated by CPG */
  Eigen::Matrix4d coupling_matrix_;

  double amplitude_mu_;
  double convergence_factor_a_;

  Eigen::Vector4d ground_multiplier_;
  Eigen::Vector4d frequency_omega_;

  Eigen::Vector4d amplitude_r_;
  Eigen::Vector4d amplitude_dr_;
  Eigen::Vector4d amplitude_d2r_;

  Eigen::Vector4d phase_theta_;
  Eigen::Vector4d phase_dtheta_;

  double coupling_weight_;
  double swing_frequency_;
  double stance_frequency_;
  double ground_clearance_;
  double ground_penetration_;

  double d_step_x_;
  double d_step_y_;
};

#endif // CENTRAL_PATTERN_GENERATOR_HPP
