standing_pose_server:
  ros__parameters:
    standing_joint_positions:
      FL_hip_joint: 0.1
      FL_thigh_joint: 0.8
      FL_calf_joint: -1.5
      FR_hip_joint: -0.1
      FR_thigh_joint: 0.8
      FR_calf_joint: -1.5
      RL_hip_joint: 0.1
      RL_thigh_joint: 1.0
      RL_calf_joint: -1.5
      RR_hip_joint: -0.1
      RR_thigh_joint: 1.0
      RR_calf_joint: -1.5
    seconds_to_stand: 3
